- client/src/mocks/ListAnimalsMock/ListAnimalsMock.json
- client/src/mocks/ListAnimalsMock/index.js
- client/src/mocks/index.js
Modelo de animalesn con 4 datos, 2 perros 2 gatos
> ListAnimalMock

- client/src/App.js
- client/src/index.js
- client/src/mocks/ListAnimalsMock/ListAnimalsMock.json
- client/src/mocks/ListFundationMock/ListFundationMock.json
Se agregaron mas animales en el ListAnimalsMock. Tambien se agrego la propiedad pets a cada obj de foundation arr 
BACK: 
@Lauti0122 
Hay que agregar la prop pets al modelo de fundacion (arreglo de obj que contiene los animales de dicha fundacion)
FRONT:
@gioacchinogioffre 
Cuando veas revisa que este todo como corresponde por las dudas! Si necesitas que fixee algo avisame
> MOCK LISTS UPDATED

- client/src/actions/index.js
- client/src/components/Adopt/Adopt.js
- client/src/components/Adopt/Adopt.module.css
- client/src/components/Adopt/Card.js
- client/src/reducers/index.js
- Creo componente card ( Pueden usarlo si en otras secciones necesitan renderizar algun animal)
- Creo nueva action para obtener todos los animales
* Asi se veria con las cards renderizadas :
* Use la action de fundation para poder filtrar por foundation:
> feat (components/adopt) render animals cards

- client/src/actions/index.js
- client/src/mocks/ListAnimalsMock/ListAnimalsMock.json
- client/src/reducers/index.js
- Solucione los conflictos que se generaron en las actions, reducer y los mocks.  Con esta PR deberia volver a funcionar todo con normalidad.
> Conflicts fixed

- client/src/actions/index.js
- client/src/components/Adopt/Adopt.js
- client/src/components/Adopt/Card.js
- client/src/components/Adopt/Filters/FilterByType.js
- client/src/reducers/index.js
> Actions n component filters

- client/package.json
- client/src/components/Home/Home.js
- client/src/components/SliderFoundation/SliderFoundation.js
- client/src/components/SliderFoundation/SliderFoundation.module.css
- client/src/mocks/ListFundationMock/ListFundationMock.js
En la ruta /home se renderiza el slider de las fundaciones ( sin estilos por el momento )
El nuevo componente esta insertado por encima de la etiqueta <section> que anteriormente contenia las fundaciones
Agregue tambien un mock en formato js para poder importar las fundaciones ( aunque no lo deje conectado, pero esta por si lo quieren usar )
npm install react-slick --save
npm install slick-carousel --save
> ft/SliderFoundation(component) -> npm install react-slick --save

- client/src/components/About us/AboutUs.js
añadi los link de github que faltaban, falta solo el de lisan
> add github´s links

- client/src/components/Footer/Footer.js
- client/src/components/Footer/Footer.module.css
- client/src/components/Home/Home.module.css
- client/src/components/SliderFoundation/SliderFoundation.js
- client/src/components/SliderFoundation/SliderFoundation.module.css
> Agregue estilos al Footer y le puse un top para espaciar del contenido de la pagina

- client/src/components/ProfileFoundation/AdoptionRequests/AdoptionRequests.css
- client/src/components/ProfileFoundation/AdoptionRequests/AdoptionRequests.jsx
- client/src/components/ProfileFoundation/Data/Data.js
- client/src/components/ProfileFoundation/EditProfile/EditProfile.css
- client/src/components/ProfileFoundation/EditProfile/EditProfile.jsx
- client/src/components/ProfileFoundation/Inbox/Inbox.css
- client/src/components/ProfileFoundation/Inbox/Inbox.jsx
- client/src/components/ProfileFoundation/InfoPets/InfoPets.css
- client/src/components/ProfileFoundation/InfoPets/InfoPets.jsx
- client/src/components/ProfileFoundation/ProfileFoundation.js
- client/src/components/ProfileFoundation/Sidebar/Sidebar.jsx
Agregue un componente por tab, dependiendo de un state! ya estan enlazados los componentes como para que empecemos a trabajar ahi
> Refactor -> tab mounts new component

- client/src/components/PostPet/PostPet.js
Guardar en claudinary imagen en formulario
> cloudinary

- client/src/components/PostPet/PostPet.js
- client/src/components/Profile/PostNews/PostNews.js
- client/src/redux/actions/index.js
Conecte el front con Cloudinary, como hizo Cris con los pets pero con las News.
Por otra parte tambien conecto cloudinary con el back ( desde postNews).
@EnuarM / @CRISTIAN0026, si queren mañana  antes de meternos en la reunion con Jorge revisamos la parte que armaron de Pets para conectarlo con el Back.
> feat(profile/postNews) cloudinary

- client/src/components/ProfileFoundation/AdoptionRequests/AdoptionRequests.jsx
- client/src/components/ProfileFoundation/Data/Data.js
- client/src/components/ProfileFoundation/Donations/Donations.css
- client/src/components/ProfileFoundation/Donations/Donations.jsx
- client/src/components/ProfileFoundation/Inbox/Inbox.jsx
- client/src/components/ProfileFoundation/InfoPets/InfoPets.css
- client/src/components/ProfileFoundation/InfoPets/InfoPets.jsx
- client/src/components/ProfileFoundation/ProfileFoundation.js
- client/src/components/ProfileFoundation/RightSide/RightSide.css
- client/src/components/ProfileFoundation/RightSide/RightSide.jsx
Agregue mas items. Conecte con Post News y Post Pet, aunque hay que hacer un buen refactor para que quede mejor. Una vez que estos componentes esten finalizados y centralizados ajusto los estilos!
Nuevos items: 
-Mis Huellas ( Renderiza todos los pets de la fundacion )
-Post News ( Trae el componente al panel de fundacion )
-Post Pet ( Trae el componente al panel de fundacion )
-Donaciones ( Hay que plantear como desplegar la info )
-Solicitudes ( Tiene info mokeada )
> ItemAdded: +PostNew, +PostPet, +Donation, +MyPets

- client/src/components/ProductDetail/ProductDetail.js
- client/src/components/ProductDetail/ProductDetail.module.css
- client/src/redux/reducers/index.js
> adding Styles

- client/src/redux/actions/index.js
- client/src/redux/reducers/index.js
> solution errors

- client/src/components/PostPet/PostPet.js
- client/src/redux/actions/index.js
> feat(components/postPets) connection with DB n cloudinary

- client/src/components/ProductDetail/ProductDetail.js
añadi las alertas, intente hacer la modificacion de los puntos del usuario pero hay un problemita :(
> alerts added

- client/src/components/Adopt/AdoptionForm/AdoptionForm.module.css
- client/src/components/Adopt/AdoptionForm/Form.js
- client/src/components/Adopt/AdoptionForm/Form.module.css
- client/src/redux/actions/index.js
- Conecto el formulario de adopción con el back. ( No pude chequear si el codigo funciona por el tema del deployado, despues tenemos que revisar si efectivamente se sube la info a la db).
- Modifico el diseño para que sea responsive :
Computadora: 
Celular
:
> Feat adopt form

- client/src/App.js
- client/src/components/PostPet/PostPet.js
- client/src/components/PostPet/PostPet.module.css
- Arreglo bug del form al postear animales.
- Le agrego estilo responsive
1024px:
720px:
> fix bugs and responsive behaviour - postPetsForm

- client/src/components/ProfileUser/EditDataForm.js
Hola!,  hice un pequeño cambio en el form en UserProfile  porque no coincidía el input de "Te gustaría ofrecerte como persona de tránsito"(SI) con el back y tenia error al despachar la action.  Solucionado sacando una simple tile :)))
> error component/ProfileUser/EditDataForm

- client/src/components/ProfileFoundation/AdoptionRequests/AdoptionRequests.jsx
- client/src/components/ProfileFoundation/AdoptionRequests/AdoptionRequests.module.css
- client/src/components/ProfileFoundation/Data/Data.js
- client/src/components/ProfileFoundation/Donations/Donations.jsx
- client/src/components/ProfileFoundation/Donations/Donations.module.css
- client/src/components/ProfileFoundation/InfoPets/InfoPets.jsx
- client/src/components/ProfileFoundation/InfoPets/InfoPets.module.css
- client/src/components/ProfileFoundation/ProfileFoundation.js
- client/src/components/ProfileFoundation/ProfileFoundation.module.css
- client/src/components/ProfileFoundation/Table/Table.jsx
- client/src/components/ProfileFoundation/Table/Table.module.css
Actualice las tablas, me falta hacer un par de cosas mas pero ya casi queda terminado
Una vez me actualice con el back dejo las conexiones hechas
> refactor -> table pagination + status 

- client/src/components/Adopt/Adopt.js
- client/src/components/Adopt/Adopt.module.css
- client/src/components/Adopt/Aside/Aside.js
- client/src/components/Adopt/Card.js
- Le agrego estilo a las cards
- Agrego un aside con la opcion de ver los pets likeados y limpiar los filtros
> Adopt cards

- client/src/components/ProfileUser/Drawer.js
- client/src/components/ProfileUser/EditDataForm.js
pequeño pr, solo agregue el boton de cerrar sesion y cambie algo en el form pero quiero trabajar con todo actualizado
> add button & change userData form

- client/package.json
- client/src/components/PetStore/ItemCard.js
- client/src/components/PetStore/ShoppingCart.js
- client/src/components/PetStore/ShoppingCart.module.css
- client/src/components/PetStore/Store.js
- client/src/components/PetStore/Store.module.css
- client/src/components/ProfileAdmin/Foundations/Foundations.css
- client/src/components/ProfileAdmin/Users/Users.css
- client/src/redux/actions/index.js
-Le hice unos upgrades interesantes a la tienda
-No les pongo foto porque me gustaría que jueguen un poquito a ver que encuentran de raro, que les gusta y que les gustaría cambiar
(HINT) Prueben con usuarios autenticados y sin autenticar.
Faltarían los filtros y el css de la tienda y sale !
> Upgrade store

- client/src/components/Adopt/Adopt.js
- client/src/components/Adopt/Adopt.module.css
- client/src/components/Adopt/Aside/Aside.js
- client/src/components/Adopt/Card.js
- client/src/components/Adopt/Filters/Filters.js
- client/src/components/Adopt/Filters/Paginate.js
- Le doy funcionalidad al paginado
- Modifico el navbar para que se puedan ver los filtros
> Adopt bugs

- client/src/components/ProfileFoundation/AdoptionRequests/AdoptionRequests.jsx
- client/src/components/ProfileUser/EditDataForm.module.css
- client/src/components/ProfileUser/Table/DonationTable.css
- client/src/components/ProfileUser/Table/DonationTable.jsx
- client/src/components/ProfileUser/Table/RequestTable.css
- client/src/components/ProfileUser/Table/RequestTable.jsx
Gente ya deje las tablas con la info lista, falta darle estilos que mañana lo vamos a charlar con Santi y Lauti para definir un mismo estilo en todas las tablas.
> refactor UserProfile

- client/src/components/About us/AboutUs.js
- client/src/components/ProductDetail/ProductDetail.js
- client/src/components/ProfileUser/Drawer.js
- client/src/components/ProfileUser/EditDataForm.js
- client/src/components/ProfileUser/EditDataForm.module.css
- client/src/components/ProfileUser/ProfileUser.js
- client/src/components/ProfileUser/Table/DonationTable.jsx
- client/src/components/ProfileUser/Table/RequestTable.jsx
Holis otro pr mas, modifique el color del background del form del usuario. Quiero hablarlo con Lauti y Santi asi dejamos un modelo parecido en los 3 perfiles. Tambien estoy a la espera de que Licha haga el include del nombre de la fundacion asi en las tablas mostramos eso. Arregle todos los warnigs en los componentes que yo trabaje.
> User profile styles

- client/src/components/ProfileUser/Table/DonationTable.jsx
- client/src/components/ProfileUser/Table/RequestTable.jsx
Ahi hice que se muestren el nombre de las fundaciones en las dos tablas en vez del id :D
> FoundationName

- client/src/components/About us/AboutUs.js
- client/src/components/Donate/Donate.js
- client/src/components/Foundation/Aside.js
- client/src/components/Foundation/Foundation.js
- client/src/components/Foundation/Foundation.module.css
- client/src/components/Foundation/PetsSlick.js
- client/src/components/Foundation/PostMessage/Form.module.css
- client/src/components/GoogleMaps/GoogleMaps.module.css
- client/src/components/Huellitas/Huellitas.js
- Incluí footer en componentes Huellitas, Donar, Nosotros, y en el detalle de la fundación.
- Acomodé el form en cuanto a estilos y posiciones par que no se desplacen los inputs cuando hay errores.
- Modifiqué disposición de algunas cosas dentro de la sección
> include_footer

- client/src/components/Adopt/Adopt.js
- client/src/components/Adopt/Card.js
- client/src/components/Adopt/Filters/Filters.js
- Arreglo renderizado de pets, ahora si la fundacion se deshabilito los pets de esa fundacion no aparecen.
- Conecto la función de Likes con el back.
> Adopt user

- client/package.json
- client/src/components/Adopt/Adopt.js
- client/src/components/Home/Home.js
Agrego una animacion al scrollear en el home y en el componente adopt, son cambios muy chiquitos, pero quedan muy buen, despues les muestro
> feat(home-adopt) scroll animation

- client/src/components/Adopt/Adopt.js
- client/src/components/Contact/Contact.js
- client/src/components/Donate/Donate.js
- client/src/components/Footer/Footer.js
- client/src/components/Home/Home.js
- client/src/components/Huellitas/Huellitas.js
- client/src/components/NavBar/NavBar.js
- client/src/components/PetStore/Store.js
- client/src/components/Profile/ProfileMenu.js
- client/src/components/ProfileFoundation/AdoptionRequests/AdoptionRequests.jsx
- client/src/components/ProfileFoundation/Table/Table.jsx
- client/src/redux/actions/index.js
- client/src/redux/reducers/index.js
Le agregue un scrollTo a cada componente de los links del footer, tambien hice la funcionalidad para actualizar el estado de las RequestAdopts y el estado del Pet,  y otros cambios
> Footer links

- client/src/components/PetStore/ItemCard.js
- client/src/components/PetStore/Store.js
alert cuando se agregan productos al carrito
> mini fix store

- client/src/components/Adopt/Adopt.module.css
- client/src/components/Footer/Footer.module.css
- client/src/components/NavBar/NavBar.js
- client/src/components/ProfileUser/Drawer.js
- client/src/index.css
Arreglo un bug de los likes con el local storage
Agrego un par de estilitos
> Fix likes functionality

- client/src/components/Adopt/AdoptionForm/AdoptionForm.js
- client/src/components/Adopt/AdoptionForm/AdoptionForm.module.css
- client/src/components/Adopt/AdoptionForm/Form.js
- client/src/components/Adopt/AdoptionForm/Form.module.css
- client/src/components/Foundation/PetsSlick.js
- client/src/components/Home/News/CampaignCard.js
- client/src/components/Home/News/CampaignCard.module.css
- client/src/components/Home/News/NewsCard.js
- client/src/components/Home/News/NewsCard.module.css
- client/src/components/Profile/ProfileMenu.js
- client/src/components/SliderFoundation/SliderFoundation.module.css
Modifiqué estilos del formulario de adopción
> adoption_form/styles

- client/src/components/ProfileAdmin/EditProfile/EditDataForm.module.css
- client/src/components/ProfileAdmin/EditProfile/EditProfile.jsx
> modify form editProfile

- client/src/components/ProfileUser/EditDataForm.js
- client/src/components/ProfileUser/EditDataForm.module.css
Form de la data del usuario :D faltaran algunos estilos pero la funcionalidad esta al 100%
> userData form

- client/src/components/Adopt/Adopt.module.css
- client/src/components/Adopt/Filters/FilterByFoundation.js
- client/src/components/NavBar/NavBar.module.css
- client/src/index.css
-  Arreglo la lista de opciones de fundaciones para que solo aparezcan las habilitadas.
-  Achico un poco el navbar
-  Arreglo conflicto entre la navbar de adopt y la del header.
> fix(component/adopt) bug foundationFilter

- client/src/App.js
- client/src/components/Adopt/AdoptionForm/Form.js
- client/src/components/Adopt/AdoptionForm/Form.module.css
> Style forms

- client/src/components/Adopt/Adopt.module.css
- client/src/components/Adopt/Card.js
- Le cambio el color de fondo a las cards de los pets por un color mas claro.
- Tristemente tuve que sacar que el filtro de adoptar quede pegado al top porque perdia visibilidad con las cards.
- Arrego el estilo de los filtros.
- Arreglo un bug que habia con el hover de cards que hacia que se muevan las demas.
> fix(components/adopt) styles bugs

- client/src/components/Home/Home.js
agrego email de bienvenida al registrarse
> email-register
